//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JSMS.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JSMS.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account closed.
        /// </summary>
        public static string AccountClosed {
            get {
                return ResourceManager.GetString("AccountClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounting.
        /// </summary>
        public static string Accounting {
            get {
                return ResourceManager.GetString("Accounting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounting Management.
        /// </summary>
        public static string AccountingManagement {
            get {
                return ResourceManager.GetString("AccountingManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I already have an account?.
        /// </summary>
        public static string AlreadyAccount {
            get {
                return ResourceManager.GetString("AlreadyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This staff has check-in for today.
        /// </summary>
        public static string AlreadyCheckIn {
            get {
                return ResourceManager.GetString("AlreadyCheckIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicant.
        /// </summary>
        public static string Applicant {
            get {
                return ResourceManager.GetString("Applicant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicant Infomations.
        /// </summary>
        public static string ApplicantInfo {
            get {
                return ResourceManager.GetString("ApplicantInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicant List.
        /// </summary>
        public static string ApplicantList {
            get {
                return ResourceManager.GetString("ApplicantList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicant Management.
        /// </summary>
        public static string ApplicantManagement {
            get {
                return ResourceManager.GetString("ApplicantManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicant passed in Short-List.
        /// </summary>
        public static string ApplicantPassedShortList {
            get {
                return ResourceManager.GetString("ApplicantPassedShortList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicant passed in Recruitment.
        /// </summary>
        public static string ApplicantPassRecruitment {
            get {
                return ResourceManager.GetString("ApplicantPassRecruitment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of applicants selected.
        /// </summary>
        public static string ApplicantSelected {
            get {
                return ResourceManager.GetString("ApplicantSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of shortlisted applicants.
        /// </summary>
        public static string ApplicantShortList {
            get {
                return ResourceManager.GetString("ApplicantShortList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistance.
        /// </summary>
        public static string Assistance {
            get {
                return ResourceManager.GetString("Assistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment.
        /// </summary>
        public static string Attachment {
            get {
                return ResourceManager.GetString("Attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance.
        /// </summary>
        public static string Attendance {
            get {
                return ResourceManager.GetString("Attendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance Infomations.
        /// </summary>
        public static string AttendanceInfo {
            get {
                return ResourceManager.GetString("AttendanceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance List of Staff.
        /// </summary>
        public static string AttendanceList {
            get {
                return ResourceManager.GetString("AttendanceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance Management.
        /// </summary>
        public static string AttendanceManagement {
            get {
                return ResourceManager.GetString("AttendanceManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        public static string Auto {
            get {
                return ResourceManager.GetString("Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Account :.
        /// </summary>
        public static string BankAccount {
            get {
                return ResourceManager.GetString("BankAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behavior.
        /// </summary>
        public static string Behavior {
            get {
                return ResourceManager.GetString("Behavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behavior Infomations.
        /// </summary>
        public static string BehaviorInfo {
            get {
                return ResourceManager.GetString("BehaviorInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate of Applicant Behavior.
        /// </summary>
        public static string BehaviorList {
            get {
                return ResourceManager.GetString("BehaviorList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behavior​ Management.
        /// </summary>
        public static string BehaviorManagement {
            get {
                return ResourceManager.GetString("BehaviorManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate.
        /// </summary>
        public static string Calculate {
            get {
                return ResourceManager.GetString("Calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        public static string Calendar {
            get {
                return ResourceManager.GetString("Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambodia.
        /// </summary>
        public static string Cambodia {
            get {
                return ResourceManager.GetString("Cambodia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Career.
        /// </summary>
        public static string Career {
            get {
                return ResourceManager.GetString("Career", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Change Language.
        /// </summary>
        public static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-in date.
        /// </summary>
        public static string CheckIn {
            get {
                return ResourceManager.GetString("CheckIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking in attendance daily.
        /// </summary>
        public static string CheckInDaily {
            get {
                return ResourceManager.GetString("CheckInDaily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-out date.
        /// </summary>
        public static string CheckOut {
            get {
                return ResourceManager.GetString("CheckOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking out attendance daily.
        /// </summary>
        public static string CheckOutDaily {
            get {
                return ResourceManager.GetString("CheckOutDaily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        public static string Client {
            get {
                return ResourceManager.GetString("Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Infomations.
        /// </summary>
        public static string ClientInfo {
            get {
                return ResourceManager.GetString("ClientInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer List.
        /// </summary>
        public static string ClientList {
            get {
                return ResourceManager.GetString("ClientList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Management.
        /// </summary>
        public static string ClientManagement {
            get {
                return ResourceManager.GetString("ClientManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Number.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commune.
        /// </summary>
        public static string Commune {
            get {
                return ResourceManager.GetString("Commune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jinglong Security Co.,Ltd.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmed By.
        /// </summary>
        public static string Confirmed {
            get {
                return ResourceManager.GetString("Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Price.
        /// </summary>
        public static string Cost {
            get {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost must be greater than 0.
        /// </summary>
        public static string CostGreater {
            get {
                return ResourceManager.GetString("CostGreater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count From.
        /// </summary>
        public static string CountFrom {
            get {
                return ResourceManager.GetString("CountFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Account.
        /// </summary>
        public static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Account.
        /// </summary>
        public static string CreateNewAccount {
            get {
                return ResourceManager.GetString("CreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Type.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Address.
        /// </summary>
        public static string CurrentAddress {
            get {
                return ResourceManager.GetString("CurrentAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data has been created.
        /// </summary>
        public static string DataCreated {
            get {
                return ResourceManager.GetString("DataCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data has been deleted.
        /// </summary>
        public static string DataDeleted {
            get {
                return ResourceManager.GetString("DataDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data has been redo.
        /// </summary>
        public static string DataRedo {
            get {
                return ResourceManager.GetString("DataRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data has been updated.
        /// </summary>
        public static string DataUpdated {
            get {
                return ResourceManager.GetString("DataUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District.
        /// </summary>
        public static string District {
            get {
                return ResourceManager.GetString("District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        public static string DOB {
            get {
                return ResourceManager.GetString("DOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag and drop files here, or click to select files.
        /// </summary>
        public static string DragAndDrop {
            get {
                return ResourceManager.GetString("DragAndDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit .
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education.
        /// </summary>
        public static string Education {
            get {
                return ResourceManager.GetString("Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchang Rate.
        /// </summary>
        public static string ExchangRate {
            get {
                return ResourceManager.GetString("ExchangRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This applicant has already been confirmed.
        /// </summary>
        public static string ExistApplicant {
            get {
                return ResourceManager.GetString("ExistApplicant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This code is already in use.
        /// </summary>
        public static string ExistCode {
            get {
                return ResourceManager.GetString("ExistCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice number already exists.
        /// </summary>
        public static string ExistInvioce {
            get {
                return ResourceManager.GetString("ExistInvioce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This applicant is already in the selection process.
        /// </summary>
        public static string ExistRecruitment {
            get {
                return ResourceManager.GetString("ExistRecruitment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This applicant​​ already on the shortlist.
        /// </summary>
        public static string ExistShorList {
            get {
                return ResourceManager.GetString("ExistShorList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username already registered.
        /// </summary>
        public static string ExistUsername {
            get {
                return ResourceManager.GetString("ExistUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense.
        /// </summary>
        public static string Expense {
            get {
                return ResourceManager.GetString("Expense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense cannot exceed total income.
        /// </summary>
        public static string ExpenseCannot {
            get {
                return ResourceManager.GetString("ExpenseCannot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost of materials and supplies.
        /// </summary>
        public static string ExpenseCostMateial {
            get {
                return ResourceManager.GetString("ExpenseCostMateial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance costs.
        /// </summary>
        public static string ExpenseInsurence {
            get {
                return ResourceManager.GetString("ExpenseInsurence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance and repair fees.
        /// </summary>
        public static string ExpenseMaintenance {
            get {
                return ResourceManager.GetString("ExpenseMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General-Expense Management.
        /// </summary>
        public static string ExpenseManagement {
            get {
                return ResourceManager.GetString("ExpenseManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketing and Advertising Costs.
        /// </summary>
        public static string ExpenseMarkrting {
            get {
                return ResourceManager.GetString("ExpenseMarkrting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material costs.
        /// </summary>
        public static string ExpenseMaterial {
            get {
                return ResourceManager.GetString("ExpenseMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location rental costs.
        /// </summary>
        public static string ExpenseRent {
            get {
                return ResourceManager.GetString("ExpenseRent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary and wages of employees.
        /// </summary>
        public static string ExpenseSalary {
            get {
                return ResourceManager.GetString("ExpenseSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense on Salary Management.
        /// </summary>
        public static string ExpenseSalaryManagement {
            get {
                return ResourceManager.GetString("ExpenseSalaryManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company supply (electricity, water).
        /// </summary>
        public static string ExpenseSupport {
            get {
                return ResourceManager.GetString("ExpenseSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay monthly tax.
        /// </summary>
        public static string ExpenseTaxMonthly {
            get {
                return ResourceManager.GetString("ExpenseTaxMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay annual tax.
        /// </summary>
        public static string ExpenseTaxYearly {
            get {
                return ResourceManager.GetString("ExpenseTaxYearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel and entertainment expenses.
        /// </summary>
        public static string ExpenseTravel {
            get {
                return ResourceManager.GetString("ExpenseTravel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense Type.
        /// </summary>
        public static string ExpenseType {
            get {
                return ResourceManager.GetString("ExpenseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax fines.
        /// </summary>
        public static string ExpeseTaxFine {
            get {
                return ResourceManager.GetString("ExpeseTaxFine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget.
        /// </summary>
        public static string Forget {
            get {
                return ResourceManager.GetString("Forget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full-Time.
        /// </summary>
        public static string FullTime {
            get {
                return ResourceManager.GetString("FullTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gaurantor List.
        /// </summary>
        public static string GaurantorList {
            get {
                return ResourceManager.GetString("GaurantorList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Ledger.
        /// </summary>
        public static string GeneralLedger {
            get {
                return ResourceManager.GetString("GeneralLedger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General-Manager.
        /// </summary>
        public static string GeneralManager {
            get {
                return ResourceManager.GetString("GeneralManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Invoice Information.
        /// </summary>
        public static string GenerateInvoice {
            get {
                return ResourceManager.GetString("GenerateInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Work.
        /// </summary>
        public static string GoToWork {
            get {
                return ResourceManager.GetString("GoToWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guarantor.
        /// </summary>
        public static string Guarantor {
            get {
                return ResourceManager.GetString("Guarantor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guarantor Infomations.
        /// </summary>
        public static string GuarantorInfo {
            get {
                return ResourceManager.GetString("GuarantorInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guarantor Management.
        /// </summary>
        public static string GuarantorManagement {
            get {
                return ResourceManager.GetString("GuarantorManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High School.
        /// </summary>
        public static string HighSchool {
            get {
                return ResourceManager.GetString("HighSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human Resource.
        /// </summary>
        public static string HR {
            get {
                return ResourceManager.GetString("HR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income.
        /// </summary>
        public static string Income {
            get {
                return ResourceManager.GetString("Income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertising revenue.
        /// </summary>
        public static string IncomeAds {
            get {
                return ResourceManager.GetString("IncomeAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earnings from comment value.
        /// </summary>
        public static string IncomeAdvisor {
            get {
                return ResourceManager.GetString("IncomeAdvisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenue from service fee.
        /// </summary>
        public static string IncomeCost {
            get {
                return ResourceManager.GetString("IncomeCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income from interest income.
        /// </summary>
        public static string IncomeExpensive {
            get {
                return ResourceManager.GetString("IncomeExpensive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General-Income Infomations.
        /// </summary>
        public static string IncomeInfo {
            get {
                return ResourceManager.GetString("IncomeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General-Income Management.
        /// </summary>
        public static string IncomeManagement {
            get {
                return ResourceManager.GetString("IncomeManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income or Expense.
        /// </summary>
        public static string IncomeOrExpense {
            get {
                return ResourceManager.GetString("IncomeOrExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income from Salary.
        /// </summary>
        public static string IncomeSalary {
            get {
                return ResourceManager.GetString("IncomeSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income​ from Salary Management.
        /// </summary>
        public static string IncomeSalaryManagement {
            get {
                return ResourceManager.GetString("IncomeSalaryManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenue from product sales.
        /// </summary>
        public static string IncomeSell {
            get {
                return ResourceManager.GetString("IncomeSell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenue from sales of services.
        /// </summary>
        public static string IncomeService {
            get {
                return ResourceManager.GetString("IncomeService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income from voluntary sponsorship.
        /// </summary>
        public static string IncomeSponsored {
            get {
                return ResourceManager.GetString("IncomeSponsored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income from state sponsorship.
        /// </summary>
        public static string IncomeState {
            get {
                return ResourceManager.GetString("IncomeState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenue from taxes.
        /// </summary>
        public static string IncomeTax {
            get {
                return ResourceManager.GetString("IncomeTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income Type.
        /// </summary>
        public static string IncomeType {
            get {
                return ResourceManager.GetString("IncomeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add or remove.
        /// </summary>
        public static string InOrOut {
            get {
                return ResourceManager.GetString("InOrOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input .
        /// </summary>
        public static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instead.
        /// </summary>
        public static string Instead {
            get {
                return ResourceManager.GetString("Instead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid registration data.
        /// </summary>
        public static string InvalidData {
            get {
                return ResourceManager.GetString("InvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login attempt.
        /// </summary>
        public static string InvalidLoginAttempt {
            get {
                return ResourceManager.GetString("InvalidLoginAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid model.
        /// </summary>
        public static string InvalidModel {
            get {
                return ResourceManager.GetString("InvalidModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice​.
        /// </summary>
        public static string Invoice {
            get {
                return ResourceManager.GetString("Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Shared Date.
        /// </summary>
        public static string InvoiceDay {
            get {
                return ResourceManager.GetString("InvoiceDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice.
        /// </summary>
        public static string InvoiceKh {
            get {
                return ResourceManager.GetString("InvoiceKh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Number.
        /// </summary>
        public static string InvoiceNumber {
            get {
                return ResourceManager.GetString("InvoiceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Generate Page.
        /// </summary>
        public static string InvoicePage {
            get {
                return ResourceManager.GetString("InvoicePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Applicant.
        /// </summary>
        public static string JobApplicant {
            get {
                return ResourceManager.GetString("JobApplicant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job-Applicant Infomation.
        /// </summary>
        public static string JobApplicantInfo {
            get {
                return ResourceManager.GetString("JobApplicantInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job applicant management.
        /// </summary>
        public static string JobApplicantList {
            get {
                return ResourceManager.GetString("JobApplicantList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joining Date.
        /// </summary>
        public static string JoiningDate {
            get {
                return ResourceManager.GetString("JoiningDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khmer.
        /// </summary>
        public static string KH {
            get {
                return ResourceManager.GetString("KH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khmer.
        /// </summary>
        public static string Khmer {
            get {
                return ResourceManager.GetString("Khmer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KHR (៛).
        /// </summary>
        public static string KHR {
            get {
                return ResourceManager.GetString("KHR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Late.
        /// </summary>
        public static string Late {
            get {
                return ResourceManager.GetString("Late", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login into System.
        /// </summary>
        public static string LoginInto {
            get {
                return ResourceManager.GetString("LoginInto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully logged in.
        /// </summary>
        public static string LoginSuccess {
            get {
                return ResourceManager.GetString("LoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login with Username and Password.
        /// </summary>
        public static string LoginWith {
            get {
                return ResourceManager.GetString("LoginWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main​ Salary.
        /// </summary>
        public static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find by Month.
        /// </summary>
        public static string Monthly {
            get {
                return ResourceManager.GetString("Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Infor.
        /// </summary>
        public static string MoreInfo {
            get {
                return ResourceManager.GetString("MoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morning.
        /// </summary>
        public static string Morning {
            get {
                return ResourceManager.GetString("Morning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of Applcant.
        /// </summary>
        public static string NameOfApplcant {
            get {
                return ResourceManager.GetString("NameOfApplcant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of Guarantor.
        /// </summary>
        public static string NameOfGuarantor {
            get {
                return ResourceManager.GetString("NameOfGuarantor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National.
        /// </summary>
        public static string National {
            get {
                return ResourceManager.GetString("National", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        public static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New applicant.
        /// </summary>
        public static string NewApplicant {
            get {
                return ResourceManager.GetString("NewApplicant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night.
        /// </summary>
        public static string Night {
            get {
                return ResourceManager.GetString("Night", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Account for Login?.
        /// </summary>
        public static string NoAccount {
            get {
                return ResourceManager.GetString("NoAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goods in stock are not enough.
        /// </summary>
        public static string NotEnough {
            get {
                return ResourceManager.GetString("NotEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data found.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Studied.
        /// </summary>
        public static string NotStudied {
            get {
                return ResourceManager.GetString("NotStudied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This staff has not check-in for today .
        /// </summary>
        public static string NotYetIn {
            get {
                return ResourceManager.GetString("NotYetIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National Religion King.
        /// </summary>
        public static string NRK {
            get {
                return ResourceManager.GetString("NRK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password is invalid.
        /// </summary>
        public static string OldPasswordInvalid {
            get {
                return ResourceManager.GetString("OldPasswordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online​ Applicant.
        /// </summary>
        public static string OnlineApplicant {
            get {
                return ResourceManager.GetString("OnlineApplicant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online​ Client.
        /// </summary>
        public static string OnlineClient {
            get {
                return ResourceManager.GetString("OnlineClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actitvity Type.
        /// </summary>
        public static string OtherGLType {
            get {
                return ResourceManager.GetString("OtherGLType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of Work.
        /// </summary>
        public static string OutOfWork {
            get {
                return ResourceManager.GetString("OutOfWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        public static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Name.
        /// </summary>
        public static string OwnerName {
            get {
                return ResourceManager.GetString("OwnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part-Time.
        /// </summary>
        public static string PartTime {
            get {
                return ResourceManager.GetString("PartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passed.
        /// </summary>
        public static string Passed {
            get {
                return ResourceManager.GetString("Passed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This applicant is already an staff.
        /// </summary>
        public static string PassesAsStaff {
            get {
                return ResourceManager.GetString("PassesAsStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 8 characters long.
        /// </summary>
        public static string PasswordMustBe8Char {
            get {
                return ResourceManager.GetString("PasswordMustBe8Char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match.
        /// </summary>
        public static string PasswordNotMatch {
            get {
                return ResourceManager.GetString("PasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment​ Method.
        /// </summary>
        public static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Type.
        /// </summary>
        public static string PaymentType {
            get {
                return ResourceManager.GetString("PaymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People.
        /// </summary>
        public static string People {
            get {
                return ResourceManager.GetString("People", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone line 1.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone line 2 (Optional).
        /// </summary>
        public static string Phone2 {
            get {
                return ResourceManager.GetString("Phone2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Login into your account.
        /// </summary>
        public static string PleaseLogin {
            get {
                return ResourceManager.GetString("PleaseLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place of Birth.
        /// </summary>
        public static string POB {
            get {
                return ResourceManager.GetString("POB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premier Maney.
        /// </summary>
        public static string Premier {
            get {
                return ResourceManager.GetString("Premier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        public static string PresentOrAbsent {
            get {
                return ResourceManager.GetString("PresentOrAbsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary School.
        /// </summary>
        public static string PrimarySchool {
            get {
                return ResourceManager.GetString("PrimarySchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procduct Management.
        /// </summary>
        public static string ProcductManagement {
            get {
                return ResourceManager.GetString("ProcductManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product&apos;s Name.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product List of Item Available.
        /// </summary>
        public static string ProductAvailable {
            get {
                return ResourceManager.GetString("ProductAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Infomations.
        /// </summary>
        public static string ProductInfo {
            get {
                return ResourceManager.GetString("ProductInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of available items.
        /// </summary>
        public static string ProductList {
            get {
                return ResourceManager.GetString("ProductList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province.
        /// </summary>
        public static string Province {
            get {
                return ResourceManager.GetString("Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose.
        /// </summary>
        public static string Purpose {
            get {
                return ResourceManager.GetString("Purpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recruitment.
        /// </summary>
        public static string Recruitment {
            get {
                return ResourceManager.GetString("Recruitment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recruitment Infomations.
        /// </summary>
        public static string RecruitmentInfo {
            get {
                return ResourceManager.GetString("RecruitmentInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recruitment Management.
        /// </summary>
        public static string RecruitmentManagement {
            get {
                return ResourceManager.GetString("RecruitmentManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string Redo {
            get {
                return ResourceManager.GetString("Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Online.
        /// </summary>
        public static string RegisterOnline {
            get {
                return ResourceManager.GetString("RegisterOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Online Management.
        /// </summary>
        public static string RegisterOnlineManagement {
            get {
                return ResourceManager.GetString("RegisterOnlineManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remain-Stock.
        /// </summary>
        public static string RemainStock {
            get {
                return ResourceManager.GetString("RemainStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remain-Stock Management.
        /// </summary>
        public static string RemainStockManagement {
            get {
                return ResourceManager.GetString("RemainStockManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Stock Available.
        /// </summary>
        public static string ReportStockAvailable {
            get {
                return ResourceManager.GetString("ReportStockAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request security guards.
        /// </summary>
        public static string RequestGuard {
            get {
                return ResourceManager.GetString("RequestGuard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Permission.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Permission.
        /// </summary>
        public static string RolePermission {
            get {
                return ResourceManager.GetString("RolePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary.
        /// </summary>
        public static string Salary {
            get {
                return ResourceManager.GetString("Salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary​ Payment.
        /// </summary>
        public static string SalaryPayment {
            get {
                return ResourceManager.GetString("SalaryPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary report.
        /// </summary>
        public static string SalaryReport {
            get {
                return ResourceManager.GetString("SalaryReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary School.
        /// </summary>
        public static string SecondarySchool {
            get {
                return ResourceManager.GetString("SecondarySchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecting.
        /// </summary>
        public static string Selecting {
            get {
                return ResourceManager.GetString("Selecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an staff ID.
        /// </summary>
        public static string SelectStaff {
            get {
                return ResourceManager.GetString("SelectStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Service.
        /// </summary>
        public static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Type.
        /// </summary>
        public static string ShiftType {
            get {
                return ResourceManager.GetString("ShiftType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short​​ List.
        /// </summary>
        public static string ShortList {
            get {
                return ResourceManager.GetString("ShortList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short-List Infomations.
        /// </summary>
        public static string ShortListInfo {
            get {
                return ResourceManager.GetString("ShortListInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short-List Management.
        /// </summary>
        public static string ShortListManagement {
            get {
                return ResourceManager.GetString("ShortListManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all.
        /// </summary>
        public static string ShowData {
            get {
                return ResourceManager.GetString("ShowData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff.
        /// </summary>
        public static string Staff {
            get {
                return ResourceManager.GetString("Staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Infomations.
        /// </summary>
        public static string StaffInfo {
            get {
                return ResourceManager.GetString("StaffInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff List.
        /// </summary>
        public static string StaffList {
            get {
                return ResourceManager.GetString("StaffList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Management.
        /// </summary>
        public static string StaffManagement {
            get {
                return ResourceManager.GetString("StaffManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standing at :.
        /// </summary>
        public static string Standing {
            get {
                return ResourceManager.GetString("Standing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Product.
        /// </summary>
        public static string Stock {
            get {
                return ResourceManager.GetString("Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock-In.
        /// </summary>
        public static string StockIn {
            get {
                return ResourceManager.GetString("StockIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Management.
        /// </summary>
        public static string StockManagement {
            get {
                return ResourceManager.GetString("StockManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock-Out.
        /// </summary>
        public static string StockOut {
            get {
                return ResourceManager.GetString("StockOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock-Product Infomations.
        /// </summary>
        public static string StockProductInfo {
            get {
                return ResourceManager.GetString("StockProductInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Type.
        /// </summary>
        public static string StockType {
            get {
                return ResourceManager.GetString("StockType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Total.
        /// </summary>
        public static string SubTotal {
            get {
                return ResourceManager.GetString("SubTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary Information.
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax.
        /// </summary>
        public static string Tax {
            get {
                return ResourceManager.GetString("Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        public static string Telephone {
            get {
                return ResourceManager.GetString("Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you..!.
        /// </summary>
        public static string ThankYou {
            get {
                return ResourceManager.GetString("ThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for logging in.
        /// </summary>
        public static string ThankYouIn {
            get {
                return ResourceManager.GetString("ThankYouIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for logging out.
        /// </summary>
        public static string ThankYouOut {
            get {
                return ResourceManager.GetString("ThankYouOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your data still the same.
        /// </summary>
        public static string TheSame {
            get {
                return ResourceManager.GetString("TheSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That want to delete this data.
        /// </summary>
        public static string ToDelete {
            get {
                return ResourceManager.GetString("ToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Absent.
        /// </summary>
        public static string TotalAbsent {
            get {
                return ResourceManager.GetString("TotalAbsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Present​.
        /// </summary>
        public static string TotalPresent {
            get {
                return ResourceManager.GetString("TotalPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction.
        /// </summary>
        public static string Transaction {
            get {
                return ResourceManager.GetString("Transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Management.
        /// </summary>
        public static string TransactionManagement {
            get {
                return ResourceManager.GetString("TransactionManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price.
        /// </summary>
        public static string UnitPrice {
            get {
                return ResourceManager.GetString("UnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to University.
        /// </summary>
        public static string University {
            get {
                return ResourceManager.GetString("University", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Until .
        /// </summary>
        public static string Until {
            get {
                return ResourceManager.GetString("Until", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated.
        /// </summary>
        public static string Updated {
            get {
                return ResourceManager.GetString("Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Image.
        /// </summary>
        public static string UploadImage {
            get {
                return ResourceManager.GetString("UploadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USD ($).
        /// </summary>
        public static string USD {
            get {
                return ResourceManager.GetString("USD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Infomations.
        /// </summary>
        public static string UserInfo {
            get {
                return ResourceManager.GetString("UserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Management.
        /// </summary>
        public static string UserManagement {
            get {
                return ResourceManager.GetString("UserManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string UserProfile {
            get {
                return ResourceManager.GetString("UserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of users by role.
        /// </summary>
        public static string UserRole {
            get {
                return ResourceManager.GetString("UserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VATTIN.
        /// </summary>
        public static string VATTIN {
            get {
                return ResourceManager.GetString("VATTIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification required.
        /// </summary>
        public static string VerificationRequired {
            get {
                return ResourceManager.GetString("VerificationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vice-Manager.
        /// </summary>
        public static string ViceManager {
            get {
                return ResourceManager.GetString("ViceManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Village.
        /// </summary>
        public static string Village {
            get {
                return ResourceManager.GetString("Village", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Jinglong.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to JingLong Security.
        /// </summary>
        public static string WelcomeTo {
            get {
                return ResourceManager.GetString("WelcomeTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your.
        /// </summary>
        public static string Your {
            get {
                return ResourceManager.GetString("Your", resourceCulture);
            }
        }
    }
}
